// File generated by FlutterFire CLI.
// Firebase configuration options for EliteMed - GDG Hackathon

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDemoKey_GDG_Hackathon_Web',
    appId: '1:123456789000:web:abcdef1234567890',
    messagingSenderId: '123456789000',
    projectId: 'elitemed-gdg-hackathon',
    authDomain: 'elitemed-gdg-hackathon.firebaseapp.com',
    storageBucket: 'elitemed-gdg-hackathon.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDemoKey_GDG_Hackathon_Android',
    appId: '1:123456789000:android:abcdef1234567890',
    messagingSenderId: '123456789000',
    projectId: 'elitemed-gdg-hackathon',
    storageBucket: 'elitemed-gdg-hackathon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDemoKey_GDG_Hackathon_iOS',
    appId: '1:123456789000:ios:abcdef1234567890',
    messagingSenderId: '123456789000',
    projectId: 'elitemed-gdg-hackathon',
    storageBucket: 'elitemed-gdg-hackathon.appspot.com',
    iosBundleId: 'com.example.localtest',
  );
}
